version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build-macos:
    macos:
      xcode: 15.4.0
    steps:
      - checkout
      - node/install:
          node-version: '18.18.0'
      - node/install-packages
      - run:
          name: Build for macOS
          command: npm run make
      - store_artifacts:
          path: out/make
          destination: macos-builds

  build-windows:
    docker:
      - image: cimg/node:18.18.0
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Install Build Dependencies
          command: |
            sudo dpkg --add-architecture i386
            sudo apt-get update
            sudo apt-get install -y wine32 wine64 rpm
      - run:
          name: Build for Windows
          command: npm run make
      - store_artifacts:
          path: out/make
          destination: windows-builds

workflows:
  version: 2
  build:
    jobs:
      - build-macos
      - build-windows
