version: 2.1
executors:
  macos-executor:
    macos:
      xcode: 15.4.0
    resource_class: m2pro.medium
  windows-executor:
    machine:
      image: windows-server-2022-gui:current
    resource_class: windows.medium

commands:
  install-dependencies:
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
jobs:
  build-macos:
    executor: macos-executor
    steps:
      - checkout
      - install-dependencies
      - run:
          name: Install macOS Certificates
          command: |
            # Add your certificate installation steps here if needed
            echo "Setting up certificates..."
      - run:
          name: Build macOS App
          command: npm run make -- --platform=darwin
      - store_artifacts:
          path: out/make
          destination: macos-builds

  build-windows:
    executor: windows-executor
    steps:
      - checkout
      - run:
          name: Install Node.js
          command: |
            choco install nodejs -y --version=18.15.0
      - install-dependencies
      - run:
          name: Build Windows App
          command: npm run make -- --platform=win32
      - store_artifacts:
          path: out/make
          destination: windows-builds
workflows:
  version: 2
  build-and-test:
    jobs:
      - build-macos:
          filters:
            branches:
              only: main
      - build-windows:
          filters:
            branches:
              only: main
